services:
  db:
    image: postgres:15
    container_name: odooDB
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    restart: no

  odoo:
    image: odoo:18
    container_name: odooApp
    depends_on:
      - db
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
    restart: no

  nginx:
    image: nginx:latest
    container_name: odooProxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - odoo
    restart: no

volumes:
  odoo-db-data:
  odoo-web-data: