from . import delivery_order
from . import delivery_order_line
from . import delivery_claim
from . import delivery_driver_rating
from . import res_users_delivery
from . import delivery_schedule
from . import delivery_sector
from . import delivery_state_log
from . import delivery_rating
from . import delivery_zone
from . import payment_transaction
from . import product_product
from . import res_config_settings
from . import sale_delivery_bridge
from . import sale_order
