{
    'name': 'Gestión de Restaurante La Comanda - Reservas de Mesa',
    'version': '1.0',
    'category': 'Restaurant',
    'summary': 'Módulo para gestión de reservas de mesa y mesas',
    'author': 'Alejandro Andrade, Kevin Carrasco, Marco Serrano, Jonathan Lozada, Juan López, Elvis Flores',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'website',
        'calendar',
        'crm',
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/table_views.xml',
        'views/reservation_views.xml',
        'views/menu.xml',
        'views/website.xml',
        'data/demo_data.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
